#### 整合freemarker
spring:
    freemarker:
        cache: false
        charset: UTF-8
        check-template-location: true
        content-type: text/html
        expose-request-attributes: true
        expose-session-attributes: true
        request-context-attribute: request
        suffix: .ftl
        template-loader-path:
        - classpath:/templates
    application:
        name: app-july-portal-pay-web
###服务注册到eureka地址
eureka:
  client:
    service-url:
           defaultZone: http://192.168.124.131:8080/eureka
server:
  port: 8050
  
redis:
  hostname: 47.91.214.23
  port: 6379
  password:
 

xxl-sso:
  excluded:
    paths: 
xxl:
  sso:
    server: http://xxlssoserver.com:8500/xxl-sso-server
    logout:
      path: /logout
    redis:
      address: redis://47.91.214.23:6379


